name: PPO
description: "Projeto Orientado (IFPE)"
publish_to: 'PDV+'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  permission_handler: ^11.1.0  
  shared_preferences: ^2.2.1 
  path_provider: ^2.1.2
  path: ^1.8.3
  provider: ^6.0.5
  badges: ^3.1.2
  intl: ^0.18.1
  connectivity_plus: ^5.0.1  
  sqflite: ^2.3.1
  sqflite_common_ffi: ^2.3.0+2
  dio: ^5.3.2
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  url_launcher: ^6.2.4
  crypto: ^3.0.3
  font_awesome_flutter: ^10.5.0
  dropdown_button2: ^2.3.9
  curved_navigation_bar: ^1.0.3
  brasil_fields: ^1.14.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  step_progress_indicator: ^1.0.2
  location: ^5.0.3
  auto_size_text: ^3.0.0
  device_info_plus: ^9.1.1
  calendar_date_picker2: ^0.5.3
  #Impressao
  sunmi_printer_plus: ^2.1.2
  flutter_pdfview: ^1.2.7
  pdf: ^3.8.4
  esc_pos_utils: ^1.1.0
  print_bluetooth_thermal: ^1.0.9
  image: ^3.0.2
  pdf_render: ^1.4.5
  esc_pos_printer: ^4.1.0 
  xml: ^6.5.0
  #Outros
  ftpconnect: ^2.0.5
  flutter_dotenv: ^5.1.0
  collection: ^1.17.2
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/grupos/
    - assets/clientes/
    - assets/produtos/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf